import os
import shlex
import subprocess

Import("env")
with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

if "CONFIG_TOOLCHAIN_PREFIX" in os.environ:
    env["RANLIB"] = '${_concat(GCCPREFIX, "ranlib", GCCSUFFIX, __env__)}'
    env["RANLIBCOM"] = "$RANLIB $TARGET"
    env["ARFLAGS"] = ["rcs"]

SRCS = Glob("src/*.c*")
INCLUDE = [ADir("."), ADir("include")]
PRIVATE_INCLUDE = []
REQUIREMENTS = ["lvgl_component", "pthread"]
if "CONFIG_V9_5_LV_USE_SDL" not in os.environ:
    REQUIREMENTS += ["input", "xkbcommon", "udev"]
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
if "CONFIG_V9_5_LV_USE_SDL" not in os.environ:
    LDFLAGS += ["-lutil"]
LINK_SEARCH_PATH = []
STATIC_FILES = []
FREETYPE_INCLUDE = None


def pkg_config_flags(kind, package):
    try:
        return shlex.split(subprocess.check_output(["pkg-config", kind, package], text=True))
    except Exception:
        return []


def append_pkg_config(package, definitions, requirements, link_search_path, ldflags):
    for flag in pkg_config_flags("--cflags", package):
        definitions.append(flag)
    for flag in pkg_config_flags("--libs", package):
        if flag.startswith("-L"):
            link_search_path.append(flag[2:])
        elif flag.startswith("-l"):
            requirements.append(flag[2:])
        else:
            ldflags.append(flag)

static_sysroot = os.environ.get("CARDPUTERZERO_STATIC_LIB_SYSROOT") or os.environ.get("CONFIG_TOOLCHAIN_SYSROOT")
if static_sysroot:
    sysroot = static_sysroot.strip('"')
    freetype_include = os.path.join(sysroot, "usr", "include", "freetype2")
    if os.path.isdir(freetype_include):
        INCLUDE += [freetype_include]
        FREETYPE_INCLUDE = freetype_include
    multiarch_lib = os.path.join(sysroot, "usr", "lib", "aarch64-linux-gnu")
    if os.path.isdir(multiarch_lib):
        LDFLAGS += [
            f"--sysroot={sysroot}",
            f"-B{multiarch_lib}",
            f"-Wl,-rpath-link,{multiarch_lib}",
        ]
        LINK_SEARCH_PATH += [multiarch_lib]

lvgl_component = list(filter(lambda x: x["target"] == "lvgl_component", env["COMPONENTS"]))[0]
if FREETYPE_INCLUDE:
    for component in env["COMPONENTS"]:
        component["INCLUDE"] += [FREETYPE_INCLUDE]
if "CONFIG_V9_5_LV_USE_FREETYPE" in os.environ:
    REQUIREMENTS += ["freetype"]
if "CONFIG_V9_5_LV_USE_SDL" in os.environ:
    lvgl_component["REQUIREMENTS"] += ["SDL2"]
    lvgl_component["INCLUDE"] += ["/usr/include/SDL2"]
    for sdl_include in [
        "/opt/homebrew/include",
        "/opt/homebrew/include/SDL2",
        "/usr/local/include",
        "/usr/local/include/SDL2",
    ]:
        if os.path.exists(sdl_include):
            lvgl_component["INCLUDE"] += [sdl_include]
    for sdl_lib in ["/opt/homebrew/lib", "/usr/local/lib"]:
        if os.path.exists(sdl_lib):
            lvgl_component["LINK_SEARCH_PATH"] += [sdl_lib]
    lvgl_component["DEFINITIONS"] += ["-D_REENTRANT"]
    append_pkg_config("freetype2", lvgl_component["DEFINITIONS"], REQUIREMENTS,
                      LINK_SEARCH_PATH, LDFLAGS)
    for src in list(lvgl_component["SRCS"]):
        if "lv_sdl_keyboard.c" in str(src):
            lvgl_component["SRCS"].remove(src)

env["COMPONENTS"].append(
    {
        "target": "M5CardputerZero-AppStore",
        "SRCS": SRCS,
        "INCLUDE": INCLUDE,
        "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
        "REQUIREMENTS": REQUIREMENTS,
        "STATIC_LIB": STATIC_LIB,
        "DYNAMIC_LIB": DYNAMIC_LIB,
        "DEFINITIONS": DEFINITIONS,
        "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
        "LDFLAGS": LDFLAGS,
        "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
        "STATIC_FILES": STATIC_FILES,
        "REGISTER": "project",
    }
)
